version: '3.8'

services:
  weather-service:
    build: .
    container_name: weather-neo4j-service
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"