version: "3.8"

services:
  insect-detection-api:
    build: .
    container_name: insect-detection-api
    ports:
      - "7733:7733"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
